# Use postgres/example user/password credentials
version: '3.1'

services:

  authentication_microservice: 
    build: microservices/authentication
    environment:
      DB_URL: "postgresql_engine"
      DB_USER: "postgres"
      DB_PASSWORD: "totally_secure_password"
      KAFKA_URL: "kafka"
      KAFKA_PORT: "29092"
    ports:
      - 8090:8090
    depends_on: 
      - postgresql_engine

  logtracer_microservice: 
    build: microservices/logtracer
    environment:
      TOPIC_NAME: "logtrace"
      KAFKA_URL: "kafka"
      KAFKA_PORT: "29092"
    depends_on: 
      - postgresql_engine
      - authentication_microservice

  postgresql_engine:
    image: postgres
    environment:
      POSTGRES_PASSWORD: totally_secure_password
      POSTGRES_DB: authentication
    ports:
      - 5432:5432

# Kafka Stuff
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
