version: '3.1'

services:

  authentication_microservice: 
    build: us-east1-docker.pkg.dev/nojipiz-corp-infrastructure/microservices-workshop/authentication_microservice
    networks:
      - internal-network
    environment:
      KAFKA_URL: 'kafka_engine'
      KAFKA_PORT: "29092"
      TOPIC_NAME: "logtrace"
      DB_URL: 'jdbc:postgresql://postgresql_engine:5432/authentication'
      DB_USER: "postgres"
      DB_PASSWORD: "totally_secure_password"
    ports:
      - 8090:8090
    depends_on: 
      - postgresql_engine
      - kafka_engine

  logtracer_microservice: 
    build: us-east1-docker.pkg.dev/nojipiz-corp-infrastructure/microservices-workshop/logtracer_microservice
    networks:
      - internal-network
    environment:
      TOPIC_NAME: "logtrace"
      KAFKA_URL: 'kafka_engine'
      KAFKA_PORT: "29092"
    depends_on: 
      - kafka_engine

  parking_manager_microservice: 
    build: us-east1-docker.pkg.dev/nojipiz-corp-infrastructure/microservices-workshop/parking_manager_microservice
    ports:
      - 3042:3042

  postgresql_engine:
    image: postgres
    networks:
      - internal-network
    environment:
      POSTGRES_PASSWORD: totally_secure_password
      POSTGRES_DB: authentication
    ports:
      - 5432:5432

  # Kafka Stuff
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - internal-network
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka_engine:
    image: confluentinc/cp-kafka:latest
    hostname: kafka_engine 
    container_name: kafka_engine 
    networks:
      - internal-network
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_engine:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks:
  internal-network:
    driver: bridge
